- name: Play to grade QA
  hosts: workstation
  gather_facts: false
  vars:
    ANSIBLE_ADVANCE_GUID: 2eab
    OSP_GUID: b3ca
    OSP_DOMAIN: green.osp.opentlc.com
    OPENTLC_ID: cloud-user
  tasks:
  - name: Create In-memory Inventory
    add_host: 
      name: workstation-{{ OSP_GUID }}.{{ OSP_DOMAIN }}
      group: workstation
      ansible_user: "{{ OPENTLC_ID }}"
 

  - name: OpenStack servers
    os_server_info:
      cloud: openstack
      server: '*'
    register: openstack_info
  
  - debug: var=openstack_info
  
  - name: Check if all osp instance exist
    debug: 
      msg: "{{ openstack_info.openstack_servers | length }}"
    register: osp_instance

  - debug: var=osp_instance

  - name: Access website
    uri:
      url: "http://{{ item.public_v4 }}"
      status_code: 200
      return_content: yes
    when: 'item.hostname == "frontend"'
    loop: "{{ openstack_info.openstack_servers }}"
    register: qa_webpage
    ignore_errors: yes

  - debug: 
      msg: "{{ item.content }}"
    when: 
      - 'item.skipped | d(false) != true' 
      - '"Ansible" in item.content'
    loop: "{{ qa_webpage.results }}"

  - name: Fail
    fail:
    when: 
      - 'item.skipped | d(false) != true' 
      - '"Ansible" not in item.content'
    loop: "{{ qa_webpage.results }}"
  
- hosts: localhost
  gather_facts: false
  vars:
    ANSIBLE_ADVANCE_GUID: 2eab
  tasks:
  - name: Access website
    uri:
      url: "http://frontend1.{{ ANSIBLE_ADVANCE_GUID }}.example.opentlc.com"
      status_code: 200
      return_content: yes
    register: prod_webpage


  - name: Fail
    fail:
    when: "'Ansible' not in prod_webpage.content" 

  - name: Success
    debug: msg="Congrats Yours HW Assignment is completed"


