- name: Play to grade QA
  hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: openstack
      server: '*'
    register: openstack_info
  
  - debug: var=openstack_info
  
  - name: Check if all osp instance exist
    debug: 
      msg: "{{ openstack_info.openstack_servers | length }}"
    register: osp_instance

  - debug: var=osp_instance



  - name: Access website
    uri:
      url: "http://{{ item.public_v4 }}"
      status_code: 200
      return_content: yes
    when: 'item.hostname == "frontend"'
    loop: "{{ openstack_info.openstack_servers }}"
    register: qa_webpage
    ignore_errors: yes

 
  - debug: 
      msg: "{{ item.content }}"
    when: 
      - 'item.skipped | d(false) != true' 
      - '"Ansible" in item.content'
    loop: "{{ qa_webpage.results }}"

  - name: Fail
    fail:
    when: 
      - 'item.skipped | d(false) != true' 
      - '"Ansible" in item.content'
    loop: "{{ qa_webpage.results }}"

  
- hosts: localhost
  vars:
    ANSIBLE_ADVANCE_GUID: "{{ lookup('env','THREE_TIER_GUID') }}"
  gather_facts: false
  tasks:
  - name: Access website
    uri:
      url: "http://frontend1.{{ ANSIBLE_ADVANCE_GUID }}.example.opentlc.com"
      status_code: 200
      return_content: yes
    register: prod_webpage


  - name: Fail
    fail:
    when: "'Ansible' not in prod_webpage.content" 

  - name: Success
    debug: msg="Congrats Yours HW Assignment is completed"


